server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:blogsearch
    username: sa
    password:
    driver-class-name: org.h2.Driver

jbb:
  search-url:
    kakao: https://dapi.kakao.com/v2/search/blog
    naver: https://openapi.naver.com/v1/search/blog.json
  key:
    kakao: {key}
    naver:
      id: {id}
      secret: {secret}